# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec — builds a ONEDIR Windows app (folder, not single file).

Onedir is used deliberately: the Python runtime (incl. python3xx.dll) lives
permanently next to the executable in _internal/, so there is NO per-launch
temp extraction to %TEMP%\\_MEI… . That removes the "Failed to load Python DLL"
class of failures that onefile suffers after a self-replace update, and makes
startup faster and antivirus-friendly. The folder is wrapped into a signed
Inno Setup installer (installer/KFZManager.iss) for distribution.

Bundled data (collected into _internal/ at the matching relative path):
    * src/database/schema.sql        -> creates the database on first run
    * src/database/catalog_seed.json -> recommendation catalog seed
    * version.json                   -> the app's own version (update baseline)
    * assets/app.ico                 -> window/app icon
"""

import json
import os
import sys as _sys

block_cipher = None


def _app_version() -> str:
    try:
        with open("version.json", encoding="utf-8") as fh:
            return str(json.load(fh).get("version", "0.0.0"))
    except Exception:
        return "0.0.0"


_VERSION = _app_version()

a = Analysis(
    ['src/main.py'],
    pathex=['src'],
    binaries=[],
    datas=[
        ('src/database/schema.sql', 'src/database'),
        ('src/database/catalog_seed.json', 'src/database'),
        ('version.json', '.'),
        ('assets/app.ico', 'assets'),
    ],
    hiddenimports=[],
    hookspath=[],
    runtime_hooks=[],
    excludes=['tkinter', 'PyQt5', 'PySide6', 'PySide2', 'PyQt6.QtWebEngineCore'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,   # onedir: binaries go into COLLECT, not the exe
    name='KFZManager',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/app.ico',
    version='version_info.txt',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='KFZManager',
)

# On macOS, wrap the collected folder into a proper .app bundle. The .icns is
# generated by CI (tools/make_icns.py) before the build; if it is missing the
# bundle still builds with a generic icon.
if _sys.platform == 'darwin':
    app = BUNDLE(
        coll,
        name='KFZManager.app',
        icon='assets/app.icns' if os.path.exists('assets/app.icns') else None,
        bundle_identifier='de.mijonex.kfzmanager',
        version=_VERSION,
        info_plist={
            'CFBundleName': 'KFZManager',
            'CFBundleDisplayName': 'KFZ-Manager',
            'CFBundleShortVersionString': _VERSION,
            'CFBundleVersion': _VERSION,
            'NSHighResolutionCapable': True,
            'LSMinimumSystemVersion': '11.0',
            'LSApplicationCategoryType': 'public.app-category.utilities',
            'NSHumanReadableCopyright': 'Privat genutztes Werkzeug.',
        },
    )
