# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec — builds a ONEDIR Windows app (folder, not single file).

Onedir is used deliberately: the Python runtime (incl. python3xx.dll) lives
permanently next to the executable in _internal/, so there is NO per-launch
temp extraction to %TEMP%\\_MEI… . That removes the "Failed to load Python DLL"
class of failures that onefile suffers after a self-replace update, and makes
startup faster and antivirus-friendly. The folder is wrapped into a signed
Inno Setup installer (installer/KFZManager.iss) for distribution.

Bundled data (collected into _internal/ at the matching relative path):
    * src/database/schema.sql        -> creates the database on first run
    * src/database/catalog_seed.json -> recommendation catalog seed
    * version.json                   -> the app's own version (update baseline)
    * assets/app.ico                 -> window/app icon
"""

import json
import os
import sys as _sys

block_cipher = None


def _app_version() -> str:
    try:
        with open("version.json", encoding="utf-8") as fh:
            return str(json.load(fh).get("version", "0.0.0"))
    except Exception:
        return "0.0.0"


_VERSION = _app_version()


def _version_info_file() -> str | None:
    """Windows-Versionsressource aus version.json ERZEUGEN (kein Drift).

    Eine statisch gepflegte version_info.txt vergisst man beim Release —
    im Schwesterprojekt zeigte der Explorer deshalb über viele Versionen
    hinweg eine uralte Nummer an, während die App längst weiter war. Die
    Datei wird darum bei jedem Build aus version.json generiert (nach
    build/, gitignored). Nur Windows braucht sie.
    """
    if not _sys.platform.startswith('win'):
        return None
    parts = [int(p) for p in _VERSION.split('.') if p.isdigit()]
    quad = tuple((parts + [0, 0, 0, 0])[:4])
    dotted = '.'.join(str(n) for n in quad)
    content = f"""# AUTOGENERIERT aus version.json - nicht von Hand bearbeiten.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={quad},
    prodvers={quad},
    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable('040704b0', [
        StringStruct('CompanyName', 'Mijonex'),
        StringStruct('FileDescription', 'KFZ-Manager'),
        StringStruct('FileVersion', '{dotted}'),
        StringStruct('InternalName', 'KFZManager'),
        StringStruct('OriginalFilename', 'KFZManager.exe'),
        StringStruct('ProductName', 'KFZ-Manager'),
        StringStruct('ProductVersion', '{dotted}')
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [0x0407, 1200])])
  ]
)
"""
    os.makedirs('build', exist_ok=True)
    path = os.path.join('build', 'version_info.txt')
    with open(path, 'w', encoding='utf-8') as fh:
        fh.write(content)
    return path


_VERSION_INFO = _version_info_file()

a = Analysis(
    ['src/main.py'],
    pathex=['src'],
    binaries=[],
    datas=[
        ('src/database/schema.sql', 'src/database'),
        ('src/database/catalog_seed.json', 'src/database'),
        # Fahrzeug-Katalog: kuratierte Stammdaten + KBA-Schlüsselnummern
        # (HSN/TSN aus dem Fahrzeugschein). Beides read-only Referenzdaten.
        ('src/database/vehicle_seed.json', 'src/database'),
        ('src/database/kba_seed.csv.gz', 'src/database'),
        ('src/database/KATALOG-QUELLEN.md', 'src/database'),
        ('version.json', '.'),
        ('assets/app.ico', 'assets'),
    ],
    hiddenimports=[],
    hookspath=[],
    runtime_hooks=[],
    excludes=['tkinter', 'PyQt5', 'PySide6', 'PySide2', 'PyQt6.QtWebEngineCore'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,   # onedir: binaries go into COLLECT, not the exe
    name='KFZManager',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/app.ico',
    version=_VERSION_INFO,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='KFZManager',
)

# On macOS, wrap the collected folder into a proper .app bundle. The .icns is
# generated by CI (tools/make_icns.py) before the build; if it is missing the
# bundle still builds with a generic icon.
if _sys.platform == 'darwin':
    app = BUNDLE(
        coll,
        name='KFZManager.app',
        icon='assets/app.icns' if os.path.exists('assets/app.icns') else None,
        bundle_identifier='de.mijonex.kfzmanager',
        version=_VERSION,
        info_plist={
            'CFBundleName': 'KFZManager',
            'CFBundleDisplayName': 'KFZ-Manager',
            'CFBundleShortVersionString': _VERSION,
            'CFBundleVersion': _VERSION,
            'NSHighResolutionCapable': True,
            'LSMinimumSystemVersion': '11.0',
            'LSApplicationCategoryType': 'public.app-category.utilities',
            'NSHumanReadableCopyright': 'Privat genutztes Werkzeug.',
        },
    )
